### ISSUE TITLE
Replacement of tabs to put as an option?

### ISSUE THREAD

**Issue by Radiation-Transport** [inr-kit/numjuggler#10]
The automatic replacement of tabs often is a problem. Is there a possibility to remove this feature from the command line? If not, I would like to propose to remove it as standard feature to avoid possible problems in the reading of the modified file.

**Comment by travleev** [comment]
The replacement of tabs with spaces is currently necessary for parsing the input file lines. Leaving them as is will break parsing (for example when the tab is used to denote the continuation line). However, I added the option ``--preservetabs`` to the command line arguments that turns off the conversion of tabs into spaces.  Look to the input file with tabs [itab_](https://github.com/travleev/numjuggler/blob/optional-tab/dev_tests/itab_) and the example of invoking numjuggler in [itab.sh](https://github.com/travleev/numjuggler/blob/optional-tab/dev_tests/itab.sh).

I also modified the logic of tab-to-spaces replacement; now it exactly follows description on p. 1-3 of the Vol.II of the MCNP5 User's manual.  Please provide an usage scenario, when the tabs should be preserved -- this might help to understand how to implement it.

# IMPORTANT:
I did not work directly on the repo in inr-kit organization. Instead I've forked numjuggler to my private account, https://github.com/travleev/numjuggler. The changes described above can be found there, in the [optional-tab](https://github.com/travleev/numjuggler/tree/optional-tab) branch. 

I will address the issues already reported in this repo  in my private fork. If you want to put my attention to any new issues, please report them in my private fork.
