### ISSUE TITLE
--mode cdens

### ISSUE THREAD

**Issue by Radiation-Transport** [inr-kit/numjuggler#11]
Looking at the main.py I have noticed there is a --mode cdens option which is not described in the documentation. What is it usage? How can be used?

**Comment by travleev** [comment]
I organized documentaiton system (both for online and interactive) in [travleev/numjuggler](https://github.com/travleev/numjuggler). For the online docs see https://numjuggler.readthedocs.io/ 

It is far from complete, but the mentioned above mode is described: [cdens](https://numjuggler.readthedocs.io/cdens/).
