### ISSUE TITLE
remh mode does not work with nested hashes

### ISSUE THREAD

**Issue by Radiation-Transport** [inr-kit/numjuggler#12]
It seems that the transition to Python 3 has introduced an issue with the remh mode. If a cell description has a # that points to a cell that also has a # the script is interrupted with an error. 

In the previous Python 2 version the script worked properly in these situations.

**Comment by Radiation-Transport** [comment]
I have noticed that for some inputs the script can finish without interruption but the resulting output is incorrect.

**Comment by travleev** [comment]
Thank you very much for reporting the issues. Currently I'm busy and will address them first after 27.12.

**Comment by Radiation-Transport** [comment]
[Example.zip](https://github.com/inr-kit/numjuggler/files/3959679/Example.zip)

Thanks to you. Please find attached an example of a simplified MCNP model and the result of remh applied to it with numjuggler version of Python 2. When trying to run it with numjuggler Python 3 the script is interrupted.

**Comment by travleev** [comment]
The example input from Example.zip above is added to the set of tests as [nested_complement.i](https://github.com/travleev/numjuggler/blob/master/travis_tests/remh/nested_complement.i). The tests are passed with Python2.7 and Python3.7
