### ISSUE TITLE
import module in likefunc

### ISSUE THREAD

**Issue by vedirah** [inr-kit/numjuggler#16]
I think 'from numbering import get_numbers' in likefunc.py should read 'from numjuggler.numbering import get_numbers'
issue arose when using the 'i' expression in renum
numjuggler 2.42.34

**Comment by travleev** [comment]
Thanks for reporting this issue.

I fixed the bug in travleev/numjuggler@900f98a commit.

Please note: the inr-kit/numjuggler repository seems to be not supported, consider using [travleev/numjuggler](https://github.com/travleev/numjuggler) fork instead.
