### ISSUE TITLE
Parsing error for file with no title

### ISSUE THREAD

**Issue by dodu94** [inr-kit/numjuggler#17]
Hi, titles are optional in MCNP input files. Nevertheless, it seems that an input with no title is not parsed correctly.
The first line of the input, even if it is a cell card, is interpreted as a title and the first cell is lost from the cells block.

An example of this behaviour can be seen using this simple input:
[Sphere.txt](https://github.com/inr-kit/numjuggler/files/8049951/Sphere.txt)

and the following code:

```
from numjuggler import parser

# Input file with no title
file = 'Sphere.txt'

cards = parser.get_cards_from_input(file)
cardsDic = parser.get_blocks(cards)

# Title card should be empty
print('title line: '+cardsDic[2][0].lines[0])

# First cell has been lost due to title misread
print('First read cell: '+cardsDic[3][0].lines[0])
```

the output is:

```
title line: 1  0          -1    IMP:N=1   IMP:P=1

First read cell: 2  1 -0.302  +1 -2     IMP:N=1   IMP:P=1
```

**Comment by travleev** [comment]
Hi,

thanks for the feedback. Two comments:

1. Could you please check that the title card is optional? The MCNP 6.2 [user manual](https://mcnp.lanl.gov/pdf_files/la-ur-17-29981.pdf) says it is required, see e.g. section 2.5. The same was for MCNP-4 and MCNP-5. Was this rule changed recently?
2. This repo seems to be unmaintained. Use instead its fork https://github.com/travleev/numjuggler.

UPD: check [mip](https://github.com/travleev/mip) for input file parsing.

**Comment by dodu94** [comment]
You are right, I double-checked and titles are indeed mandatory for MCNP input so I will able to eliminate that edge case from my work. Sorry to trouble you.

About mip, thanks for the hint! at the moment though I have everything implemented in JADE (https://github.com/dodu94/JADE)  importing numjuggler and I do not have time to refactor the code.
