### ISSUE TITLE
--mode nofill <issue>

### ISSUE THREAD

**Issue by Radiation-Transport** [inr-kit/numjuggler#2]
Unfortunately the nofill mode is not working as expected. A bug seems to be present. In addition, it is not able to remove fill+tr card. May you look into it please? 

Thanks in advance,
Marco

**Comment by travleev** [comment]
Hello Marco,  could you please provide the input and the command line arguments that result in the wrong behaviuor?

**Comment by travleev** [comment]
The 'nofill' mode is undocumented. 

In the recent version, one needs to specify additionally the -u option, which should contain all universe numbers for those the 'FILL' keywords be deleted. By default this is only 0, i.e. only 'FILL=0' will be deleted.

**Comment by Radiation-Transport** [comment]
Thanks again! Now it works!
Numjuggler is the master tool!
