### ISSUE TITLE
Add test case to check the LikeFunctionBase.__call2 method. 

### ISSUE THREAD

**Issue by travleev** [inr-kit/numjuggler#8]
The ``LIkeFunction.__call2`` method is used when a log file is enquired by the user in the ``renum`` mode. Thus, the test should check the content of the ``log.txt`` file generated with the following command:

```bash
> numjuggler --mode renum --log log.txt ... input.inp > input.inp.renamed
```
In the above command the dots ``...`` must be replaced with particular renumbering rules, for example ``-c 5``.

**Comment by dvp2015** [comment]
I think, this is fixed in the recent pull request

**Comment by dvp2015** [comment]
I've added the test case, trying to freeze the functionality, but on the way I've also removed the __call2  method: it's  not needed actually.
I think, the issue can be closed.  Probably there's a need to increase test coverage for the module, but this is another issue.
